version: '3.8'

services:

  redis:
    image: redis:7-alpine
  django:
    container_name: django
    build:
      context: ./pruebatec
      dockerfile: DockerFile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./pruebatec:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: "1"
      SECRET_KEY: "1234hjhj1234"
      ALLOWED_HOST: "localhost,127.0.0.1,0.0.0.0"
    depends_on:
      - redis
  celery:
    container_name: celery
    build:
      context: ./pruebatec
      dockerfile: DockerFile
    volumes:
      - ./pruebatec:/usr/src/app
    environment:
      DEBUG: "1"
      SECRET_KEY: "1234hjhj1234"
      ALLOWED_HOST: "localhost,127.0.0.1,0.0.0.0"
    depends_on:
      - redis


